// flow-typed signature: 0ed622dd5235fa169bfe1ff32ca50641
// flow-typed version: <<STUB>>/eslint-plugin-objects_v^1.1.1/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-objects'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-objects' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-objects/lib/rules/no-object-properties-first-line' {
  declare module.exports: any;
}

declare module 'eslint-plugin-objects/lib/rules/no-object-properties-last-line' {
  declare module.exports: any;
}

declare module 'eslint-plugin-objects/lib/rules/no-object-properties-one-line' {
  declare module.exports: any;
}

declare module 'eslint-plugin-objects/lib/rules/no-object-property-split' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-objects/index' {
  declare module.exports: $Exports<'eslint-plugin-objects'>;
}
declare module 'eslint-plugin-objects/index.js' {
  declare module.exports: $Exports<'eslint-plugin-objects'>;
}
declare module 'eslint-plugin-objects/lib/rules/no-object-properties-first-line.js' {
  declare module.exports: $Exports<'eslint-plugin-objects/lib/rules/no-object-properties-first-line'>;
}
declare module 'eslint-plugin-objects/lib/rules/no-object-properties-last-line.js' {
  declare module.exports: $Exports<'eslint-plugin-objects/lib/rules/no-object-properties-last-line'>;
}
declare module 'eslint-plugin-objects/lib/rules/no-object-properties-one-line.js' {
  declare module.exports: $Exports<'eslint-plugin-objects/lib/rules/no-object-properties-one-line'>;
}
declare module 'eslint-plugin-objects/lib/rules/no-object-property-split.js' {
  declare module.exports: $Exports<'eslint-plugin-objects/lib/rules/no-object-property-split'>;
}
