// flow-typed signature: 409d0e033d1682ca4602c5a4992af6e9
// flow-typed version: <<STUB>>/eslint-config-expeek_v^1.3.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-expeek'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-expeek' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-expeek/index' {
  declare module.exports: $Exports<'eslint-config-expeek'>;
}
declare module 'eslint-config-expeek/index.js' {
  declare module.exports: $Exports<'eslint-config-expeek'>;
}
